// @generated by tools/codegen/generate-contracts.mjs; DO NOT EDIT.
#![forbid(unsafe_code)]

use serde::Serialize;

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
pub struct ErrorDescriptor {
    pub code: &'static str,
    pub number: u32,
    pub default_message: &'static str,
}

impl ErrorDescriptor {
    pub const fn new(code: &'static str, number: u32, default_message: &'static str) -> Self {
        assert!(number >= 10_000 && number <= 99_999);
        Self {
            code,
            number,
            default_message,
        }
    }
}

pub mod member {
    use super::ErrorDescriptor;

    pub const SEAT_LIMIT_REACHED: ErrorDescriptor = ErrorDescriptor::new(
        "MEMBER_SEAT_LIMIT_REACHED",
        12_010,
        "成员席位已达到许可证上限",
    );
    pub const INVALID: ErrorDescriptor =
        ErrorDescriptor::new("MEMBER_INVALID", 12_001, "成员信息无效");
    pub const EMAIL_EXISTS: ErrorDescriptor =
        ErrorDescriptor::new("MEMBER_EMAIL_EXISTS", 12_002, "该邮箱已经存在");
    pub const NOT_FOUND: ErrorDescriptor =
        ErrorDescriptor::new("MEMBER_NOT_FOUND", 12_003, "成员不存在");
    pub const QUOTA_UPDATE_CONFLICT: ErrorDescriptor = ErrorDescriptor::new(
        "MEMBER_QUOTA_UPDATE_CONFLICT",
        12_011,
        "成员额度已被其他操作更新",
    );
    pub const QUOTA_GRANT_DUPLICATE: ErrorDescriptor = ErrorDescriptor::new(
        "MEMBER_QUOTA_GRANT_DUPLICATE",
        12_012,
        "该额度发放凭据已经使用",
    );
    pub const STATUS_UPDATE_CONFLICT: ErrorDescriptor = ErrorDescriptor::new(
        "MEMBER_STATUS_UPDATE_CONFLICT",
        12_013,
        "成员状态已被并发更新",
    );
    pub const CONSUMPTION_QUERY_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "ADMIN_CONSUMPTION_QUERY_INVALID",
        12_014,
        "团队消费日志查询参数无效",
    );
    pub const MODEL_ACCESS_CONFLICT: ErrorDescriptor = ErrorDescriptor::new(
        "MEMBER_MODEL_ACCESS_CONFLICT",
        12_015,
        "成员模型权限已被其他操作更新",
    );
    pub const QUOTA_ADJUSTMENT_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "MEMBER_QUOTA_ADJUSTMENT_INVALID",
        12_016,
        "额度变更内容无效，请检查 Token、图片张数和原因",
    );
    pub const MONEY_ADJUSTMENT_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "MEMBER_MONEY_ADJUSTMENT_INVALID",
        12_017,
        "金额或调整原因无效",
    );
}

pub mod admin_auth {
    use super::ErrorDescriptor;

    pub const INVALID_CREDENTIALS: ErrorDescriptor =
        ErrorDescriptor::new("ADMIN_INVALID_CREDENTIALS", 11_001, "邮箱或密码不正确");
    pub const UNAUTHENTICATED: ErrorDescriptor =
        ErrorDescriptor::new("ADMIN_UNAUTHENTICATED", 11_002, "管理员登录状态已经失效");
    pub const PASSWORD_CHANGE_REQUIRED: ErrorDescriptor = ErrorDescriptor::new(
        "ADMIN_PASSWORD_CHANGE_REQUIRED",
        11_003,
        "首次登录必须修改安装器生成的初始密码",
    );
    pub const CURRENT_PASSWORD_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "ADMIN_CURRENT_PASSWORD_INVALID",
        11_004,
        "当前管理员密码不正确",
    );
    pub const NEW_PASSWORD_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "ADMIN_NEW_PASSWORD_INVALID",
        11_005,
        "新管理员密码不符合安全要求",
    );
    pub const PASSWORD_UPDATE_CONFLICT: ErrorDescriptor = ErrorDescriptor::new(
        "ADMIN_PASSWORD_UPDATE_CONFLICT",
        11_006,
        "管理员密码已被其他操作更新，请重新登录",
    );
}

pub mod member_auth {
    use super::ErrorDescriptor;

    pub const INVALID_CREDENTIALS: ErrorDescriptor =
        ErrorDescriptor::new("MEMBER_INVALID_CREDENTIALS", 21_001, "邮箱或密码不正确");
    pub const UNAUTHENTICATED: ErrorDescriptor =
        ErrorDescriptor::new("MEMBER_UNAUTHENTICATED", 21_002, "成员登录状态已经失效");
    pub const PASSWORD_CHANGE_REQUIRED: ErrorDescriptor = ErrorDescriptor::new(
        "MEMBER_PASSWORD_CHANGE_REQUIRED",
        21_003,
        "首次登录必须修改管理员设置的初始密码",
    );
    pub const CURRENT_PASSWORD_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "MEMBER_CURRENT_PASSWORD_INVALID",
        21_004,
        "当前成员密码不正确",
    );
    pub const NEW_PASSWORD_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "MEMBER_NEW_PASSWORD_INVALID",
        21_005,
        "新成员密码不符合安全要求",
    );
    pub const PASSWORD_UPDATE_CONFLICT: ErrorDescriptor = ErrorDescriptor::new(
        "MEMBER_PASSWORD_UPDATE_CONFLICT",
        21_006,
        "成员密码已被其他操作更新，请重新登录",
    );
}

pub mod member_api_key {
    use super::ErrorDescriptor;

    pub const INVALID: ErrorDescriptor =
        ErrorDescriptor::new("API_KEY_INVALID", 22_001, "API Key 信息无效");
    pub const NOT_FOUND: ErrorDescriptor =
        ErrorDescriptor::new("API_KEY_NOT_FOUND", 22_002, "API Key 不存在或已经撤销");
    pub const UPDATE_CONFLICT: ErrorDescriptor = ErrorDescriptor::new(
        "API_KEY_UPDATE_CONFLICT",
        22_003,
        "API Key 已被其他操作更新",
    );
    pub const LIMIT_REACHED: ErrorDescriptor = ErrorDescriptor::new(
        "API_KEY_LIMIT_REACHED",
        22_004,
        "API Key 已达到许可证对每位成员的上限",
    );
}

pub mod member_usage {
    use super::ErrorDescriptor;

    pub const INVALID: ErrorDescriptor =
        ErrorDescriptor::new("MEMBER_USAGE_QUERY_INVALID", 24_001, "用量查询参数无效");
}

pub mod member_quota {
    use super::ErrorDescriptor;

    pub const INVALID: ErrorDescriptor =
        ErrorDescriptor::new("MEMBER_QUOTA_REQUEST_INVALID", 23_001, "额度申请参数无效");
    pub const PENDING_EXISTS: ErrorDescriptor = ErrorDescriptor::new(
        "MEMBER_QUOTA_REQUEST_PENDING_EXISTS",
        23_002,
        "当前已有一条待审批额度申请",
    );
    pub const NOT_FOUND: ErrorDescriptor =
        ErrorDescriptor::new("MEMBER_QUOTA_REQUEST_NOT_FOUND", 23_003, "额度申请不存在");
    pub const REVIEW_CONFLICT: ErrorDescriptor = ErrorDescriptor::new(
        "MEMBER_QUOTA_REQUEST_REVIEW_CONFLICT",
        23_004,
        "额度申请已被审批或相关额度状态已变化",
    );
    pub const VOUCHER_INVALID: ErrorDescriptor =
        ErrorDescriptor::new("VOUCHER_INVALID", 23_005, "兑换券参数或券码无效");
    pub const VOUCHER_NOT_FOUND: ErrorDescriptor =
        ErrorDescriptor::new("VOUCHER_NOT_FOUND", 23_006, "兑换券不存在");
    pub const VOUCHER_UNAVAILABLE: ErrorDescriptor = ErrorDescriptor::new(
        "VOUCHER_UNAVAILABLE",
        23_007,
        "兑换券不可用、已过期或不属于当前成员",
    );
    pub const VOUCHER_ALREADY_REDEEMED: ErrorDescriptor = ErrorDescriptor::new(
        "VOUCHER_ALREADY_REDEEMED",
        23_008,
        "当前成员已经兑换过该兑换券",
    );
    pub const VOUCHER_REDEEM_CONFLICT: ErrorDescriptor = ErrorDescriptor::new(
        "VOUCHER_REDEEM_CONFLICT",
        23_009,
        "兑换券或成员额度已被其他操作更新",
    );
    pub const VOUCHER_DELETE_CONFLICT: ErrorDescriptor = ErrorDescriptor::new(
        "VOUCHER_DELETE_CONFLICT",
        23_010,
        "兑换券已有兑换记录，必须保留审计链路",
    );
}

pub mod gateway_auth {
    use super::ErrorDescriptor;

    pub const INVALID_API_KEY: ErrorDescriptor = ErrorDescriptor::new(
        "INVALID_API_KEY",
        31_001,
        "缺少有效的 API Key 或 API Key 已失效",
    );
}

pub mod gateway_request {
    use super::ErrorDescriptor;

    pub const INVALID: ErrorDescriptor =
        ErrorDescriptor::new("INVALID_REQUEST", 32_001, "请求参数无效");
    pub const INVALID_COMPATIBILITY_MODE: ErrorDescriptor =
        ErrorDescriptor::new("INVALID_COMPATIBILITY_MODE", 32_002, "兼容模式请求头无效");
}

pub mod gateway_routing {
    use super::ErrorDescriptor;

    pub const MODEL_NOT_FOUND: ErrorDescriptor =
        ErrorDescriptor::new("MODEL_NOT_FOUND", 33_001, "模型不存在或未开放");
    pub const MODEL_ACCOUNT_NOT_READY: ErrorDescriptor = ErrorDescriptor::new(
        "MODEL_ACCOUNT_NOT_READY",
        33_002,
        "当前没有可执行该模型的有效上游凭据",
    );
    pub const MODEL_ACCESS_DENIED: ErrorDescriptor =
        ErrorDescriptor::new("MODEL_ACCESS_DENIED", 33_005, "该模型未授权给当前用户");
}

pub mod gateway_settlement {
    use super::ErrorDescriptor;

    pub const INSUFFICIENT_QUOTA: ErrorDescriptor =
        ErrorDescriptor::new("INSUFFICIENT_QUOTA", 34_001, "可用额度不足");
    pub const RESERVATION_CONFLICT: ErrorDescriptor = ErrorDescriptor::new(
        "QUOTA_RESERVATION_CONFLICT",
        34_002,
        "额度预留状态已变化，请重新发起请求",
    );
    pub const USAGE_INVALID: ErrorDescriptor =
        ErrorDescriptor::new("USAGE_SETTLEMENT_INVALID", 34_003, "上游返回的用量信息无效");
    pub const SETTLEMENT_CONFLICT: ErrorDescriptor =
        ErrorDescriptor::new("USAGE_SETTLEMENT_CONFLICT", 34_004, "额度结算状态已变化");
    pub const DUPLICATE_REQUEST: ErrorDescriptor =
        ErrorDescriptor::new("DUPLICATE_REQUEST", 34_005, "请求标识已经使用");
    pub const BILLING_PRICE_UNAVAILABLE: ErrorDescriptor = ErrorDescriptor::new(
        "BILLING_PRICE_UNAVAILABLE",
        34_006,
        "该模型尚未配置有效价格",
    );
    pub const BILLING_CALCULATION_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "BILLING_CALCULATION_INVALID",
        34_007,
        "用量无法按已配置价格计算",
    );
}

pub mod gateway_upstream {
    use super::ErrorDescriptor;

    pub const INVALID_RESPONSE: ErrorDescriptor = ErrorDescriptor::new(
        "INVALID_UPSTREAM_RESPONSE",
        35_001,
        "上游返回了无法验证的响应",
    );
    pub const REQUEST_FAILED: ErrorDescriptor =
        ErrorDescriptor::new("UPSTREAM_REQUEST_FAILED", 35_002, "上游请求执行失败");
    pub const RESPONSE_TOO_LARGE: ErrorDescriptor = ErrorDescriptor::new(
        "UPSTREAM_RESPONSE_TOO_LARGE",
        35_003,
        "上游响应超过允许大小",
    );
    pub const USAGE_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "UPSTREAM_USAGE_INVALID",
        35_004,
        "上游响应缺少有效的用量信息",
    );
    pub const IMAGE_DELIVERY_FAILED: ErrorDescriptor = ErrorDescriptor::new(
        "IMAGE_DELIVERY_FAILED",
        35_005,
        "图片已生成，但交付图片失败",
    );
}

pub mod upstream {
    use super::ErrorDescriptor;

    pub const CREDENTIAL_DUPLICATE: ErrorDescriptor = ErrorDescriptor::new(
        "UPSTREAM_CREDENTIAL_DUPLICATE",
        13_001,
        "该上游凭据已经存在，复制同一凭据不能作为独立实例",
    );
    pub const CREDENTIAL_NOT_FOUND: ErrorDescriptor =
        ErrorDescriptor::new("UPSTREAM_CREDENTIAL_NOT_FOUND", 13_002, "上游凭据不存在");
    pub const CREDENTIAL_REFRESH_CONFLICT: ErrorDescriptor = ErrorDescriptor::new(
        "UPSTREAM_CREDENTIAL_REFRESH_CONFLICT",
        13_003,
        "上游凭据已被其他刷新任务更新",
    );
    pub const CREDENTIAL_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "UPSTREAM_CREDENTIAL_INVALID",
        13_004,
        "上游凭据无效或无法解密",
    );
    pub const ACCOUNT_NOT_FOUND: ErrorDescriptor =
        ErrorDescriptor::new("UPSTREAM_ACCOUNT_NOT_FOUND", 13_005, "订阅/账号不存在");
    pub const CREDENTIAL_REFRESH_BUSY: ErrorDescriptor = ErrorDescriptor::new(
        "UPSTREAM_CREDENTIAL_REFRESH_BUSY",
        13_006,
        "该凭据实例正在刷新，请稍后重试",
    );
    pub const CREDENTIAL_REFRESH_LEASE_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "UPSTREAM_CREDENTIAL_REFRESH_LEASE_INVALID",
        13_007,
        "凭据刷新租约无效或已过期",
    );
    pub const OAUTH_SESSION_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "UPSTREAM_OAUTH_SESSION_INVALID",
        13_008,
        "上游授权会话无效或已过期",
    );
    pub const OAUTH_EXCHANGE_FAILED: ErrorDescriptor = ErrorDescriptor::new(
        "UPSTREAM_OAUTH_EXCHANGE_FAILED",
        13_009,
        "上游授权码兑换失败",
    );
    pub const OAUTH_SESSION_BUSY: ErrorDescriptor = ErrorDescriptor::new(
        "UPSTREAM_OAUTH_SESSION_BUSY",
        13_010,
        "上游授权会话正在完成",
    );
    pub const MODEL_SYNC_FAILED: ErrorDescriptor = ErrorDescriptor::new(
        "UPSTREAM_MODEL_SYNC_FAILED",
        13_011,
        "订阅/账号没有返回可用模型",
    );
    pub const ACCOUNT_INPUT_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "UPSTREAM_ACCOUNT_INPUT_INVALID",
        13_012,
        "订阅/账号管理参数无效",
    );
    pub const MODEL_NOT_FOUND: ErrorDescriptor =
        ErrorDescriptor::new("UPSTREAM_MODEL_NOT_FOUND", 13_013, "上游模型不存在");
    pub const MODEL_INPUT_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "UPSTREAM_MODEL_INPUT_INVALID",
        13_014,
        "上游模型管理参数无效",
    );
    pub const ACCOUNT_LIMIT_REACHED: ErrorDescriptor = ErrorDescriptor::new(
        "UPSTREAM_ACCOUNT_LIMIT_REACHED",
        13_015,
        "订阅/账号已达到许可证上限",
    );
    pub const CONNECTION_REVISION_CONFLICT: ErrorDescriptor = ErrorDescriptor::new(
        "UPSTREAM_CONNECTION_REVISION_CONFLICT",
        13_016,
        "API Key 连接已被其他操作更新",
    );
    pub const PLUGIN_UNAVAILABLE: ErrorDescriptor = ErrorDescriptor::new(
        "UPSTREAM_PLUGIN_UNAVAILABLE",
        13_017,
        "上游适配插件未就绪，请先配置并激活插件",
    );
}

pub mod platform {
    use super::ErrorDescriptor;

    pub const SETTINGS_INVALID: ErrorDescriptor =
        ErrorDescriptor::new("PLATFORM_SETTINGS_INVALID", 15_001, "运行配置参数无效");
    pub const SETTINGS_UPDATE_CONFLICT: ErrorDescriptor = ErrorDescriptor::new(
        "PLATFORM_SETTINGS_UPDATE_CONFLICT",
        15_002,
        "运行配置已被其他管理员更新",
    );
    pub const AUDIT_QUERY_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "PLATFORM_AUDIT_QUERY_INVALID",
        15_003,
        "安全审计查询参数无效",
    );
    pub const BILLING_PRICE_SYNC_UNSUPPORTED: ErrorDescriptor = ErrorDescriptor::new(
        "BILLING_PRICE_SYNC_UNSUPPORTED",
        15_004,
        "该模型暂无可可靠同步的官方价格，请手动配置",
    );
}

pub mod maintenance {
    use super::ErrorDescriptor;

    pub const INPUT_INVALID: ErrorDescriptor =
        ErrorDescriptor::new("MAINTENANCE_INPUT_INVALID", 15_010, "升级包或维护参数无效");
    pub const BUSY: ErrorDescriptor =
        ErrorDescriptor::new("MAINTENANCE_BUSY", 15_011, "已有升级或维护任务正在执行");
    pub const UNAVAILABLE: ErrorDescriptor =
        ErrorDescriptor::new("MAINTENANCE_UNAVAILABLE", 15_012, "升级维护功能暂时不可用");
}

pub mod license {
    use super::ErrorDescriptor;

    pub const MISSING: ErrorDescriptor =
        ErrorDescriptor::new("LICENSE_MISSING", 51_001, "尚未安装许可证");
    pub const EXPIRED: ErrorDescriptor =
        ErrorDescriptor::new("LICENSE_EXPIRED", 51_002, "许可证已到期");
    pub const INVALID: ErrorDescriptor =
        ErrorDescriptor::new("LICENSE_INVALID", 51_003, "许可证无效");
    pub const TIME_INVALID: ErrorDescriptor =
        ErrorDescriptor::new("LICENSE_TIME_INVALID", 51_004, "本机时间不满足许可证要求");
    pub const MACHINE_MISMATCH: ErrorDescriptor =
        ErrorDescriptor::new("LICENSE_MACHINE_MISMATCH", 51_005, "许可证与当前机器不匹配");
    pub const VERSION_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "LICENSE_VERSION_INVALID",
        51_006,
        "当前程序版本不满足许可证要求",
    );
    pub const ROLLBACK_REJECTED: ErrorDescriptor =
        ErrorDescriptor::new("LICENSE_ROLLBACK_REJECTED", 51_007, "检测到许可证状态回滚");
    pub const FEATURE_NOT_LICENSED: ErrorDescriptor =
        ErrorDescriptor::new("FEATURE_NOT_LICENSED", 51_008, "许可证未包含该功能");
    pub const SEAT_OVERAGE_EXPIRED: ErrorDescriptor = ErrorDescriptor::new(
        "MEMBER_SEAT_OVERAGE_EXPIRED",
        51_009,
        "成员席位超额宽限期已结束",
    );
}

pub mod backend {
    use super::ErrorDescriptor;

    pub const DATABASE_CONNECTION_FAILED: ErrorDescriptor = ErrorDescriptor::new(
        "BACKEND_DATABASE_CONNECTION_FAILED",
        91_005,
        "数据库连接失败，请检查数据库服务与连接配置",
    );
    pub const DATABASE_SCHEMA_MISMATCH: ErrorDescriptor = ErrorDescriptor::new(
        "BACKEND_DATABASE_SCHEMA_MISMATCH",
        91_006,
        "数据库结构与当前程序不匹配，请检查迁移状态",
    );
    pub const DATABASE_DECODE_FAILED: ErrorDescriptor = ErrorDescriptor::new(
        "BACKEND_DATABASE_DECODE_FAILED",
        91_010,
        "数据库字段读取失败，字段类型与当前程序不匹配",
    );
    pub const DATABASE_QUERY_FAILED: ErrorDescriptor = ErrorDescriptor::new(
        "BACKEND_DATABASE_QUERY_FAILED",
        91_007,
        "数据库查询或写入失败，请查看服务端日志",
    );
    pub const LOCAL_STATE_FAILED: ErrorDescriptor = ErrorDescriptor::new(
        "BACKEND_LOCAL_STATE_FAILED",
        91_008,
        "服务端本地状态读取或写入失败，请检查文件与权限",
    );
    pub const INTERNAL_OPERATION_FAILED: ErrorDescriptor = ErrorDescriptor::new(
        "BACKEND_INTERNAL_OPERATION_FAILED",
        91_009,
        "服务端内部操作失败，请查看服务端日志",
    );
    pub const STORAGE_NOT_CONFIGURED: ErrorDescriptor = ErrorDescriptor::new(
        "BACKEND_STORAGE_NOT_CONFIGURED",
        91_011,
        "服务端数据库尚未配置",
    );
    pub const TIME_CONVERSION_FAILED: ErrorDescriptor = ErrorDescriptor::new(
        "BACKEND_TIME_CONVERSION_FAILED",
        91_012,
        "服务端时间无法转换为存储格式",
    );
    pub const RANDOMNESS_UNAVAILABLE: ErrorDescriptor = ErrorDescriptor::new(
        "BACKEND_RANDOMNESS_UNAVAILABLE",
        91_013,
        "服务端随机数生成失败",
    );
    pub const RUNNER_TASK_ISSUER_NOT_CONFIGURED: ErrorDescriptor = ErrorDescriptor::new(
        "BACKEND_RUNNER_TASK_ISSUER_NOT_CONFIGURED",
        91_014,
        "Runner 任务签发配置缺失",
    );
    pub const TASK_EXECUTION_FAILED: ErrorDescriptor = ErrorDescriptor::new(
        "BACKEND_TASK_EXECUTION_FAILED",
        91_015,
        "服务端后台任务执行失败，请查看服务端日志",
    );
    pub const AUDIT_READ_CONFLICT: ErrorDescriptor = ErrorDescriptor::new(
        "BACKEND_AUDIT_READ_CONFLICT",
        91_016,
        "审计记录持续变化，请稍后重新读取",
    );
    pub const INSTANCE_DRAINING: ErrorDescriptor = ErrorDescriptor::new(
        "BACKEND_INSTANCE_DRAINING",
        91_003,
        "当前实例正在排空，请重试请求",
    );
    pub const REQUEST_DEADLINE_EXCEEDED: ErrorDescriptor = ErrorDescriptor::new(
        "BACKEND_REQUEST_DEADLINE_EXCEEDED",
        91_004,
        "请求处理超时，请确认操作结果",
    );
    pub const DATA_INTEGRITY_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "BACKEND_DATA_INTEGRITY_INVALID",
        91_002,
        "关键业务数据完整性校验失败",
    );
}

pub mod routing {
    use super::ErrorDescriptor;

    pub const RUNNER_NOT_READY: ErrorDescriptor =
        ErrorDescriptor::new("RUNNER_NOT_READY", 33_003, "当前没有可用的 Runner");
    pub const RETRY_FORBIDDEN: ErrorDescriptor = ErrorDescriptor::new(
        "RUNNER_RETRY_FORBIDDEN",
        33_004,
        "请求已发送到上游，不能自动切换 Runner",
    );
}

pub mod runner {
    use super::ErrorDescriptor;

    pub const PROTOCOL_INCOMPATIBLE: ErrorDescriptor = ErrorDescriptor::new(
        "RUNNER_PROTOCOL_INCOMPATIBLE",
        41_001,
        "Runner 协议版本不兼容",
    );
    pub const TASK_TICKET_INVALID: ErrorDescriptor =
        ErrorDescriptor::new("RUNNER_TASK_TICKET_INVALID", 41_002, "Runner 任务票据无效");
    pub const TASK_REPLAYED: ErrorDescriptor =
        ErrorDescriptor::new("RUNNER_TASK_REPLAYED", 41_003, "Runner 任务票据已使用");
    pub const UNAUTHENTICATED: ErrorDescriptor =
        ErrorDescriptor::new("RUNNER_UNAUTHENTICATED", 41_004, "Runner 身份凭据无效");
}

pub mod delivery {
    use super::ErrorDescriptor;

    pub const ROOT_REQUIRED: ErrorDescriptor = ErrorDescriptor::new(
        "DELIVERY_ROOT_REQUIRED",
        43_001,
        "该交付管理命令必须使用 root 权限执行",
    );
    pub const RELEASE_NOT_SELECTED: ErrorDescriptor = ErrorDescriptor::new(
        "DELIVERY_RELEASE_NOT_SELECTED",
        43_002,
        "尚未通过 init.sh 选择已签名发布包",
    );
    pub const RELEASE_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "DELIVERY_RELEASE_INVALID",
        43_003,
        "发布包签名、完整性或目录结构校验失败",
    );
    pub const MAINTENANCE_BUSY: ErrorDescriptor = ErrorDescriptor::new(
        "DELIVERY_MAINTENANCE_BUSY",
        43_004,
        "另一个安装、升级、恢复或维护操作正在执行",
    );
    pub const INSTALL_FAILED: ErrorDescriptor =
        ErrorDescriptor::new("DELIVERY_INSTALL_FAILED", 43_005, "Aster Team 安装失败");
    pub const UPGRADE_FAILED: ErrorDescriptor = ErrorDescriptor::new(
        "DELIVERY_UPGRADE_FAILED",
        43_006,
        "Aster Team 升级失败并已按安全策略处理",
    );
    pub const INPUT_INVALID: ErrorDescriptor =
        ErrorDescriptor::new("DELIVERY_INPUT_INVALID", 43_007, "交付管理命令参数无效");
    pub const FILESYSTEM_FAILED: ErrorDescriptor = ErrorDescriptor::new(
        "DELIVERY_FILESYSTEM_FAILED",
        43_008,
        "无法安全读写 Aster Team 交付文件",
    );
    pub const COMMAND_FAILED: ErrorDescriptor = ErrorDescriptor::new(
        "DELIVERY_COMMAND_FAILED",
        43_009,
        "Aster Team 底层维护命令执行失败",
    );
    pub const PLATFORM_UNSUPPORTED: ErrorDescriptor = ErrorDescriptor::new(
        "DELIVERY_PLATFORM_UNSUPPORTED",
        43_010,
        "当前 Linux 主机不满足 Aster Team 运行要求",
    );
    pub const SERVICE_FAILED: ErrorDescriptor =
        ErrorDescriptor::new("DELIVERY_SERVICE_FAILED", 43_011, "Aster Team 服务控制失败");
    pub const LICENSE_FAILED: ErrorDescriptor = ErrorDescriptor::new(
        "DELIVERY_LICENSE_FAILED",
        43_012,
        "Aster Team 离线许可证操作失败",
    );
    pub const BACKUP_FAILED: ErrorDescriptor = ErrorDescriptor::new(
        "DELIVERY_BACKUP_FAILED",
        43_013,
        "Aster Team 备份或恢复失败",
    );
    pub const RUNNER_FAILED: ErrorDescriptor = ErrorDescriptor::new(
        "DELIVERY_RUNNER_FAILED",
        43_014,
        "Aster Team Runner 管理失败",
    );
    pub const DIAGNOSTIC_FAILED: ErrorDescriptor = ErrorDescriptor::new(
        "DELIVERY_DIAGNOSTIC_FAILED",
        43_015,
        "Aster Team 主机诊断未通过",
    );
    pub const UNINSTALL_FAILED: ErrorDescriptor =
        ErrorDescriptor::new("DELIVERY_UNINSTALL_FAILED", 43_016, "Aster Team 卸载失败");
}

pub mod runner_admin {
    use super::ErrorDescriptor;

    pub const ENROLLMENT_INVALID: ErrorDescriptor = ErrorDescriptor::new(
        "RUNNER_ENROLLMENT_INVALID",
        14_001,
        "Runner 注册凭据无效或已使用",
    );
    pub const NOT_FOUND: ErrorDescriptor =
        ErrorDescriptor::new("RUNNER_NOT_FOUND", 14_002, "指定的 Runner 不存在");
    pub const INPUT_INVALID: ErrorDescriptor =
        ErrorDescriptor::new("RUNNER_INPUT_INVALID", 14_003, "Runner 配置参数无效");
    pub const LIMIT_REACHED: ErrorDescriptor =
        ErrorDescriptor::new("RUNNER_LIMIT_REACHED", 14_004, "Runner 已达到许可证上限");
}

pub const ALL: &[ErrorDescriptor] = &[
    member::SEAT_LIMIT_REACHED,
    member::INVALID,
    member::EMAIL_EXISTS,
    member::NOT_FOUND,
    member::QUOTA_UPDATE_CONFLICT,
    member::QUOTA_GRANT_DUPLICATE,
    member::STATUS_UPDATE_CONFLICT,
    member::CONSUMPTION_QUERY_INVALID,
    member::MODEL_ACCESS_CONFLICT,
    member::QUOTA_ADJUSTMENT_INVALID,
    member::MONEY_ADJUSTMENT_INVALID,
    admin_auth::INVALID_CREDENTIALS,
    admin_auth::UNAUTHENTICATED,
    admin_auth::PASSWORD_CHANGE_REQUIRED,
    admin_auth::CURRENT_PASSWORD_INVALID,
    admin_auth::NEW_PASSWORD_INVALID,
    admin_auth::PASSWORD_UPDATE_CONFLICT,
    member_auth::INVALID_CREDENTIALS,
    member_auth::UNAUTHENTICATED,
    member_auth::PASSWORD_CHANGE_REQUIRED,
    member_auth::CURRENT_PASSWORD_INVALID,
    member_auth::NEW_PASSWORD_INVALID,
    member_auth::PASSWORD_UPDATE_CONFLICT,
    member_api_key::INVALID,
    member_api_key::NOT_FOUND,
    member_api_key::UPDATE_CONFLICT,
    member_api_key::LIMIT_REACHED,
    member_usage::INVALID,
    member_quota::INVALID,
    member_quota::PENDING_EXISTS,
    member_quota::NOT_FOUND,
    member_quota::REVIEW_CONFLICT,
    member_quota::VOUCHER_INVALID,
    member_quota::VOUCHER_NOT_FOUND,
    member_quota::VOUCHER_UNAVAILABLE,
    member_quota::VOUCHER_ALREADY_REDEEMED,
    member_quota::VOUCHER_REDEEM_CONFLICT,
    member_quota::VOUCHER_DELETE_CONFLICT,
    gateway_auth::INVALID_API_KEY,
    gateway_request::INVALID,
    gateway_request::INVALID_COMPATIBILITY_MODE,
    gateway_routing::MODEL_NOT_FOUND,
    gateway_routing::MODEL_ACCOUNT_NOT_READY,
    gateway_routing::MODEL_ACCESS_DENIED,
    gateway_settlement::INSUFFICIENT_QUOTA,
    gateway_settlement::RESERVATION_CONFLICT,
    gateway_settlement::USAGE_INVALID,
    gateway_settlement::SETTLEMENT_CONFLICT,
    gateway_settlement::DUPLICATE_REQUEST,
    gateway_settlement::BILLING_PRICE_UNAVAILABLE,
    gateway_settlement::BILLING_CALCULATION_INVALID,
    gateway_upstream::INVALID_RESPONSE,
    gateway_upstream::REQUEST_FAILED,
    gateway_upstream::RESPONSE_TOO_LARGE,
    gateway_upstream::USAGE_INVALID,
    gateway_upstream::IMAGE_DELIVERY_FAILED,
    upstream::CREDENTIAL_DUPLICATE,
    upstream::CREDENTIAL_NOT_FOUND,
    upstream::CREDENTIAL_REFRESH_CONFLICT,
    upstream::CREDENTIAL_INVALID,
    upstream::ACCOUNT_NOT_FOUND,
    upstream::CREDENTIAL_REFRESH_BUSY,
    upstream::CREDENTIAL_REFRESH_LEASE_INVALID,
    upstream::OAUTH_SESSION_INVALID,
    upstream::OAUTH_EXCHANGE_FAILED,
    upstream::OAUTH_SESSION_BUSY,
    upstream::MODEL_SYNC_FAILED,
    upstream::ACCOUNT_INPUT_INVALID,
    upstream::MODEL_NOT_FOUND,
    upstream::MODEL_INPUT_INVALID,
    upstream::ACCOUNT_LIMIT_REACHED,
    upstream::CONNECTION_REVISION_CONFLICT,
    upstream::PLUGIN_UNAVAILABLE,
    platform::SETTINGS_INVALID,
    platform::SETTINGS_UPDATE_CONFLICT,
    platform::AUDIT_QUERY_INVALID,
    platform::BILLING_PRICE_SYNC_UNSUPPORTED,
    maintenance::INPUT_INVALID,
    maintenance::BUSY,
    maintenance::UNAVAILABLE,
    license::MISSING,
    license::EXPIRED,
    license::INVALID,
    license::TIME_INVALID,
    license::MACHINE_MISMATCH,
    license::VERSION_INVALID,
    license::ROLLBACK_REJECTED,
    license::FEATURE_NOT_LICENSED,
    license::SEAT_OVERAGE_EXPIRED,
    backend::DATABASE_CONNECTION_FAILED,
    backend::DATABASE_SCHEMA_MISMATCH,
    backend::DATABASE_DECODE_FAILED,
    backend::DATABASE_QUERY_FAILED,
    backend::LOCAL_STATE_FAILED,
    backend::INTERNAL_OPERATION_FAILED,
    backend::STORAGE_NOT_CONFIGURED,
    backend::TIME_CONVERSION_FAILED,
    backend::RANDOMNESS_UNAVAILABLE,
    backend::RUNNER_TASK_ISSUER_NOT_CONFIGURED,
    backend::TASK_EXECUTION_FAILED,
    backend::AUDIT_READ_CONFLICT,
    backend::INSTANCE_DRAINING,
    backend::REQUEST_DEADLINE_EXCEEDED,
    backend::DATA_INTEGRITY_INVALID,
    routing::RUNNER_NOT_READY,
    routing::RETRY_FORBIDDEN,
    runner::PROTOCOL_INCOMPATIBLE,
    runner::TASK_TICKET_INVALID,
    runner::TASK_REPLAYED,
    runner::UNAUTHENTICATED,
    delivery::ROOT_REQUIRED,
    delivery::RELEASE_NOT_SELECTED,
    delivery::RELEASE_INVALID,
    delivery::MAINTENANCE_BUSY,
    delivery::INSTALL_FAILED,
    delivery::UPGRADE_FAILED,
    delivery::INPUT_INVALID,
    delivery::FILESYSTEM_FAILED,
    delivery::COMMAND_FAILED,
    delivery::PLATFORM_UNSUPPORTED,
    delivery::SERVICE_FAILED,
    delivery::LICENSE_FAILED,
    delivery::BACKUP_FAILED,
    delivery::RUNNER_FAILED,
    delivery::DIAGNOSTIC_FAILED,
    delivery::UNINSTALL_FAILED,
    runner_admin::ENROLLMENT_INVALID,
    runner_admin::NOT_FOUND,
    runner_admin::INPUT_INVALID,
    runner_admin::LIMIT_REACHED,
];

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::ALL;

    #[test]
    fn published_numbers_and_codes_are_stable_and_unique() {
        let numbers: BTreeSet<_> = ALL.iter().map(|entry| entry.number).collect();
        let codes: BTreeSet<_> = ALL.iter().map(|entry| entry.code).collect();
        assert_eq!(numbers.len(), ALL.len());
        assert_eq!(codes.len(), ALL.len());
        assert!(
            ALL.iter()
                .all(|entry| (10_000..=99_999).contains(&entry.number))
        );
    }
}
