// Code generated by tools/codegen/generate-contracts.mjs; DO NOT EDIT.
package productcatalog

const Version uint32 = 1
const Product = "aster-team"

type FeatureSetID string
type CapabilityID string
type QuotaID string
type QuotaScope string
type BusinessOperationID string

const (
	FeatureSetStandard                 FeatureSetID        = "standard"
	CapabilityGateway                  CapabilityID        = "gateway"
	CapabilityMember                   CapabilityID        = "member"
	CapabilityRunner                   CapabilityID        = "runner"
	QuotaMemberSeats                   QuotaID             = "member_seats"
	QuotaRunners                       QuotaID             = "runners"
	QuotaUpstreamAccounts              QuotaID             = "upstream_accounts"
	QuotaApiKeysPerMember              QuotaID             = "api_keys_per_member"
	BusinessOperationUpstreamAuthorize BusinessOperationID = "upstream_authorize"
	BusinessOperationUpstreamSync      BusinessOperationID = "upstream_sync"
	BusinessOperationUpstreamRefresh   BusinessOperationID = "upstream_refresh"
	ScopeInstallation                  QuotaScope          = "installation"
	ScopeMember                        QuotaScope          = "member"
)

type Capability struct {
	ID          CapabilityID   `json:"id"`
	Label       string         `json:"label"`
	Description string         `json:"description"`
	FeatureSet  FeatureSetID   `json:"feature_set"`
	FreeDefault bool           `json:"free_default"`
	Requires    []CapabilityID `json:"requires"`
}
type Quota struct {
	ID    QuotaID    `json:"id"`
	Label string     `json:"label"`
	Unit  string     `json:"unit"`
	Scope QuotaScope `json:"scope"`
}
type BusinessOperation struct {
	ID       BusinessOperationID `json:"id"`
	Label    string              `json:"label"`
	Requires []CapabilityID      `json:"requires"`
}

func BusinessOperations() []BusinessOperation {
	return []BusinessOperation{
		{ID: BusinessOperationUpstreamAuthorize, Label: "新增订阅/账号", Requires: []CapabilityID{CapabilityGateway, CapabilityRunner}},
		{ID: BusinessOperationUpstreamSync, Label: "同步上游模型", Requires: []CapabilityID{CapabilityGateway, CapabilityRunner}},
		{ID: BusinessOperationUpstreamRefresh, Label: "人工刷新凭据", Requires: []CapabilityID{CapabilityGateway, CapabilityRunner}},
	}
}

// Return fresh slices so callers cannot mutate the catalog used by later requests.
func Capabilities() []Capability {
	return []Capability{
		{ID: CapabilityGateway, Label: "模型接入", Description: "模型兼容接口与上游接入管理", FeatureSet: FeatureSetStandard, FreeDefault: true, Requires: []CapabilityID{}},
		{ID: CapabilityMember, Label: "成员协作", Description: "成员控制台、席位与使用额度管理", FeatureSet: FeatureSetStandard, FreeDefault: true, Requires: []CapabilityID{}},
		{ID: CapabilityRunner, Label: "Runner 执行", Description: "私有运行节点与任务执行", FeatureSet: FeatureSetStandard, FreeDefault: true, Requires: []CapabilityID{}},
	}
}
func Quotas() []Quota {
	return []Quota{
		{ID: QuotaMemberSeats, Label: "成员席位", Unit: "席位", Scope: ScopeInstallation},
		{ID: QuotaRunners, Label: "Runner", Unit: "个", Scope: ScopeInstallation},
		{ID: QuotaUpstreamAccounts, Label: "订阅/账号", Unit: "个", Scope: ScopeInstallation},
		{ID: QuotaApiKeysPerMember, Label: "每人 Key", Unit: "个", Scope: ScopeMember},
	}
}
func FeatureSets() []FeatureSetID { return []FeatureSetID{FeatureSetStandard} }
func FindCapability(id CapabilityID) (Capability, bool) {
	for _, entry := range Capabilities() {
		if entry.ID == id {
			return entry, true
		}
	}
	return Capability{}, false
}
func FindQuota(id QuotaID) (Quota, bool) {
	for _, entry := range Quotas() {
		if entry.ID == id {
			return entry, true
		}
	}
	return Quota{}, false
}
