[package]
name = "asterctl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
aster-claude-config = { path = "../crates/claude-config" }
aster-codex-config = { path = "../crates/codex-config" }
clap.workspace = true
reqwest.workspace = true
rpassword.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile = "3.27.0"
tokio.workspace = true
toml_edit.workspace = true
url.workspace = true

[target.'cfg(windows)'.dependencies]
windows-registry = "0.6.1"
