import { expect } from '@playwright/test'
import { test, ownerLogin, memberLogin, createMember, createKey, captureFailures } from './real-fixtures.mjs'

test.use({ seedModels: true, actionTimeout: 10_000 })

function responseFor(page, path, method = 'GET', query = () => true) {
  return page.waitForResponse(response => {
    const url = new URL(response.url())
    return url.pathname === path && response.request().method() === method && query(url.searchParams)
  })
}
async function select(page, name, option) {
  await page.getByRole('combobox', { name, exact: true }).click()
  await page.getByRole('option', { name: option, exact: true }).click()
}
async function signIn(page, baseURL, kind, email, password) {
  await page.goto(`${baseURL}/login`)
  await page.getByLabel(kind === 'admin' ? '管理员邮箱' : '成员邮箱', { exact: true }).fill(email)
  await page.getByLabel('密码', { exact: true }).fill(password)
  const response = responseFor(page, `/api/${kind}/auth/login`, 'POST')
  await page.getByRole('button', { name: kind === 'admin' ? '进入管理端' : '进入用户端', exact: true }).click()
  expect((await response).status()).toBe(200)
}
async function changePassword(page, baseURL, kind, current, next) {
  await page.goto(`${baseURL}/account/password`)
  await page.getByLabel('当前密码', { exact: true }).fill(current)
  await page.getByLabel('新密码', { exact: true }).fill(next)
  await page.getByLabel('确认新密码', { exact: true }).fill(next)
  const response = responseFor(page, `/api/${kind}/auth/password`, 'POST')
  await page.getByRole('button', { name: '修改密码', exact: true }).click()
  expect((await response).status()).toBe(200)
  await expect(page).toHaveURL(/\/login(?:\?|$)/)
}

test('member-only supporting pages preserve settings identity and account lifecycle through real UI operations', async ({ page, browser, request, backend }, testInfo) => {
  test.setTimeout(150_000)
  const context = await browser.newContext({ locale: 'zh-CN' })
  const member = await context.newPage()
  const email = 'support@example.test'
  try {
    await ownerLogin(page, backend)
    const identity = await createMember(page, backend, email, 'Support Member')
    await memberLogin(member, backend, email)
    const adminFailures = captureFailures(page)
    const memberFailures = captureFailures(member)
    await expect(member.locator('.quota-value strong')).toHaveText('0')
    await member.goto(`${backend.member_url}/keys`)
    const key = await createKey(member, 'support-key')

    await member.goto(`${backend.member_url}/models`)
    await expect(member.getByRole('heading', { name: 'Browser Docs Model', exact: true })).toBeVisible()
    await member.getByRole('button', { name: '表格视图', exact: true }).click()
    await expect(member.getByRole('row').filter({ hasText: 'Browser Docs Model' })).toContainText('gpt-5.6-sol')
    await member.getByRole('textbox', { name: '搜索模型名称、ID、厂商或倍率', exact: true }).fill('absent-model')
    await expect(member.getByText('没有匹配的模型', { exact: true })).toBeVisible()
    await member.getByRole('textbox', { name: '搜索模型名称、ID、厂商或倍率', exact: true }).fill('gpt-5.6-sol')
    await select(member, '模型厂商', 'OpenAI')
    await expect(member.getByRole('row').filter({ hasText: 'Browser Docs Model' })).toBeVisible()

    await member.goto(`${backend.member_url}/usage`)
    await expect(member.getByRole('heading', { name: '用量分析', exact: true })).toBeVisible()
    const filteredUsage = responseFor(member, '/api/member/usage-summary', 'GET', params => params.get('api_key_id') === key.api_key.id)
    await select(member, '全部来源', /^support-key\s/)
    expect((await filteredUsage).status()).toBe(200)
    const month = responseFor(member, '/api/member/usage-summary', 'GET', params => {
      const days = (Date.parse(params.get('to')) - Date.parse(params.get('from'))) / 86_400_000
      return params.get('api_key_id') === key.api_key.id && days === 29
    })
    await member.getByRole('radio', { name: '30 天', exact: true }).click()
    const monthResponse = await month
    expect(monthResponse.status()).toBe(200)
    const monthUsage = await monthResponse.json()
    expect(monthUsage.summary.request_count).toBe(0)
    // This is the actual unused-member state; it does not prove non-empty model trend selection.
    await select(member, '模型', '全部模型')
    await member.screenshot({ path: testInfo.outputPath('member-support-usage.png'), fullPage: true })

    await page.goto(`${backend.admin_url}/settings`)
    const publicURL = 'https://support-browser.example.invalid'
    await page.getByRole('textbox', { name: /^公共 API 基础地址/ }).fill(publicURL)
    await page.getByRole('spinbutton', { name: /^用量结算倍率/ }).fill('1.25')
    const saved = responseFor(page, '/api/admin/settings', 'PUT')
    await page.getByRole('button', { name: '保存运行配置', exact: true }).click()
    expect((await saved).status()).toBe(200)
    await page.reload()
    await expect(page.getByRole('textbox', { name: /^公共 API 基础地址/ })).toHaveValue(publicURL)
    await expect(page.getByRole('spinbutton', { name: /^用量结算倍率/ })).toHaveValue('1.25')
    const documentation = responseFor(member, '/api/member/docs')
    await member.goto(`${backend.member_url}/docs`)
    const docsResponse = await documentation
    expect(docsResponse.status()).toBe(200)
    const docs = await docsResponse.json()
    expect(docs.usage_multiplier).toBe(1.25)
    expect(docs.base_urls.openai).toBe(`${publicURL}/v1`)
    await expect(member.locator('.a-copy-code').filter({ hasText: publicURL }).first()).toBeVisible()

    await page.goto(`${backend.admin_url}/users`)
    const userRow = page.getByRole('row').filter({ hasText: email })
    await userRow.getByRole('button', { name: '直接发放额度', exact: true }).click()
    const grantDialog = page.getByRole('dialog')
    await grantDialog.getByLabel(/^发放 Token/).fill('12345')
    await grantDialog.getByRole('textbox', { name: /^发放原因/ }).fill('Support page acceptance')
    const granted = responseFor(page, `/api/admin/users/${identity.id}/quota-adjustments`, 'POST')
    await grantDialog.getByRole('button', { name: '确认发放', exact: true }).click()
    expect((await granted).status()).toBe(200)
    await expect(grantDialog).toBeHidden()
    await userRow.getByRole('button', { name: '查看额度发放记录', exact: true }).click()
    await expect(page.getByRole('dialog')).toContainText('Support page acceptance')
    await expect(page.getByRole('dialog')).toContainText('+12,345')
    await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
    await member.goto(`${backend.member_url}/account`)
    await expect(member.getByRole('heading', { name: 'Support Member', exact: true })).toBeVisible()
    await expect(member.locator('.profile-card')).toContainText(email)
    await expect(member.locator('.profile-card dd').filter({ hasText: '12,345' })).toHaveCount(1)
    await member.goto(`${backend.member_url}/home`)
    await expect(member.locator('.quota-value strong')).toHaveText('12,345')

    const beforeDisableCookie = (await context.cookies()).map(cookie => `${cookie.name}=${cookie.value}`).join('; ')
    expect((await request.get(`${backend.member_url}/api/member/me`, { headers: { cookie: beforeDisableCookie } })).status()).toBe(200)
    await userRow.getByRole('button', { name: '禁用成员', exact: true }).click()
    const disabled = responseFor(page, `/api/admin/users/${identity.id}`, 'PATCH')
    await page.getByRole('dialog').getByRole('button', { name: '确认执行', exact: true }).click()
    expect((await disabled).status()).toBe(200)
    expect((await member.request.get(`${backend.member_url}/api/member/me`)).status()).toBe(401)
    await userRow.getByRole('button', { name: '启用成员', exact: true }).click()
    const enabled = responseFor(page, `/api/admin/users/${identity.id}`, 'PATCH')
    await page.getByRole('dialog').getByRole('button', { name: '确认执行', exact: true }).click()
    expect((await enabled).status()).toBe(200)
    expect((await request.get(`${backend.member_url}/api/member/me`, { headers: { cookie: beforeDisableCookie } })).status()).toBe(401)
    await signIn(member, backend.member_url, 'member', email, 'member-password-updated')
    await expect(member).toHaveURL(/\/home$/)
    const keys = await member.request.get(`${backend.member_url}/api/member/keys`)
    expect((await keys.json()).items.map(item => item.id)).toEqual([key.api_key.id])

    const oldMemberCookie = (await context.cookies()).map(cookie => `${cookie.name}=${cookie.value}`).join('; ')
    expect((await request.get(`${backend.member_url}/api/member/me`, { headers: { cookie: oldMemberCookie } })).status()).toBe(200)
    await changePassword(member, backend.member_url, 'member', 'member-password-updated', 'member-password-voluntary')
    const expiredMemberSession = await request.get(`${backend.member_url}/api/member/me`, { headers: { cookie: oldMemberCookie } })
    expect(expiredMemberSession.status()).toBe(401)
    expect(expiredMemberSession.headers()['x-aster-error-number']).toBe('21002')
    const oldMemberPassword = await request.post(`${backend.member_url}/api/member/auth/login`, { data: { email, password: 'member-password-updated' } })
    expect(oldMemberPassword.status()).toBe(401)
    expect(oldMemberPassword.headers()['x-aster-error-number']).toBe('21001')
    await signIn(member, backend.member_url, 'member', email, 'member-password-voluntary')
    await expect(member).toHaveURL(/\/home$/)

    await userRow.getByRole('button', { name: '重置成员密码', exact: true }).click()
    const reset = responseFor(page, `/api/admin/users/${identity.id}/password-reset`, 'POST')
    await page.getByRole('dialog').getByRole('button', { name: '生成临时密码', exact: true }).click()
    const resetResponse = await reset
    expect(resetResponse.status()).toBe(200)
    const temporary = (await resetResponse.json()).temporary_password
    await expect(page.getByRole('dialog').locator('.a-copy-code')).toContainText(temporary)
    await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
    expect((await member.request.get(`${backend.member_url}/api/member/me`)).status()).toBe(401)
    await signIn(member, backend.member_url, 'member', email, temporary)
    await expect(member).toHaveURL(/\/change-password$/)
    await member.getByLabel('当前初始密码', { exact: true }).fill(temporary)
    await member.getByLabel('新密码', { exact: true }).fill('member-password-recovered')
    await member.getByLabel('确认新密码', { exact: true }).fill('member-password-recovered')
    const recovered = responseFor(member, '/api/member/auth/password', 'POST')
    await member.getByRole('button', { name: '修改密码并重新登录', exact: true }).click()
    expect((await recovered).status()).toBe(200)
    await expect(member).toHaveURL(/\/login\?/)
    await signIn(member, backend.member_url, 'member', email, 'member-password-recovered')
    await expect(member).toHaveURL(/\/home$/)
    await expect(member.locator('.quota-value strong')).toHaveText('12,345')
    const preservedKeys = await member.request.get(`${backend.member_url}/api/member/keys`)
    expect(preservedKeys.status()).toBe(200)
    expect((await preservedKeys.json()).items.map(item => ({ id: item.id, status: item.status }))).toEqual([{ id: key.api_key.id, status: 'active' }])

    await page.goto(`${backend.admin_url}/audit-events`)
    const audit = responseFor(page, '/api/admin/audit-events', 'GET', params => params.get('action') === 'settings.update' && params.get('outcome') === 'succeeded')
    await select(page, '动作', '修改运行配置')
    await select(page, '结果', '成功')
    const auditResponse = await audit
    expect(auditResponse.status()).toBe(200)
    const events = await auditResponse.json()
    expect(events.items).toHaveLength(1)
    expect(events.items[0].action).toBe('settings.update')
    await expect(page.locator('.audit-table tbody tr')).toHaveCount(1)
    await expect(page.locator('.audit-table tbody')).toContainText('修改运行配置')
    await expect(page.locator('.audit-table tbody')).toContainText('owner@example.test')
    await page.screenshot({ path: testInfo.outputPath('admin-support-audit.png'), fullPage: true })
    const oldAdminCookie = (await page.context().cookies()).map(cookie => `${cookie.name}=${cookie.value}`).join('; ')
    expect((await request.get(`${backend.admin_url}/api/admin/me`, { headers: { cookie: oldAdminCookie } })).status()).toBe(200)
    await changePassword(page, backend.admin_url, 'admin', 'owner-password-updated', 'owner-password-voluntary')
    const expiredAdminSession = await request.get(`${backend.admin_url}/api/admin/me`, { headers: { cookie: oldAdminCookie } })
    expect(expiredAdminSession.status()).toBe(401)
    expect(expiredAdminSession.headers()['x-aster-error-number']).toBe('11002')
    const oldAdminPassword = await request.post(`${backend.admin_url}/api/admin/auth/login`, { data: { email: 'owner@example.test', password: 'owner-password-updated' } })
    expect(oldAdminPassword.status()).toBe(401)
    expect(oldAdminPassword.headers()['x-aster-error-number']).toBe('11001')
    await signIn(page, backend.admin_url, 'admin', 'owner@example.test', 'owner-password-voluntary')
    await expect(page).toHaveURL(/\/overview$/)
    await page.goto(`${backend.admin_url}/settings`)
    await expect(page.getByRole('textbox', { name: /^公共 API 基础地址/ })).toHaveValue(publicURL)
    expect(adminFailures).toEqual([])
    expect(memberFailures).toEqual([])
  } finally { await context.close() }
})
