import { expect } from '@playwright/test'
import { test, ownerLogin, memberLogin, createMember, createKey, importLicense, captureFailures } from './real-fixtures.mjs'

test.use({ freeSwitch: true })

test('administrator reduces disabled member Keys and explicitly applies bundled free rights', async ({ page, browser, backend }, testInfo) => {
  await ownerLogin(page, backend)
  const identity = await createMember(page, backend, 'downgrade@example.test', '整理成员')
  await page.goto(`${backend.admin_url}/license`)
  expect((await importLicense(page, backend.license_files.paid)).status()).toBe(200)
  const memberContext = await browser.newContext({ locale: 'zh-CN' })
  try {
    const member = await memberContext.newPage()
    await memberLogin(member, backend, 'downgrade@example.test')
    await member.goto(`${backend.member_url}/keys`)
    for (const name of ['保留 Key 一', '保留 Key 二', '准备撤销的 Key']) await createKey(member, name)
    await page.goto(`${backend.admin_url}/users`)
    await page.getByRole('button', { name: '禁用成员', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: '确认执行', exact: true }).click()
    await expect(page.getByRole('button', { name: '启用成员', exact: true })).toBeVisible()
    const failures = captureFailures(page)
    await page.goto(`${backend.admin_url}/license`)
    const panel = page.getByRole('region', { name: '切换免费版', exact: true })
    await expect(panel.getByRole('button', { name: '切换免费版', exact: true })).toBeDisabled()
    await expect(panel.getByRole('heading', { name: '整理成员 3 Key' })).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath('free-switch-capacity.png'), fullPage: true, animations: 'disabled' })
    await panel.locator('.free-key').filter({ hasText: '准备撤销的 Key' }).getByRole('button', { name: '撤销 Key', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: '确认撤销', exact: true }).click()
    await expect(panel.getByRole('button', { name: '切换免费版', exact: true })).toBeEnabled()
    await page.setViewportSize({ width: 390, height: 720 })
    await expect.poll(() => page.locator('.console-sidebar').evaluate(element => element.getBoundingClientRect().right)).toBeLessThanOrEqual(0)
    await page.evaluate(() => window.scrollTo(0, 0))
    await page.screenshot({ path: testInfo.outputPath('free-switch-mobile.png'), fullPage: true, animations: 'disabled' })
    await panel.getByRole('button', { name: '切换免费版', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: '确认切换', exact: true }).click()
    await expect(page.getByRole('heading', { name: '免费版已启用', exact: true })).toBeVisible()
    expect(failures).toEqual([])
    const status = await (await page.request.get(`${backend.admin_url}/api/admin/license`)).json()
    expect(status.license.quotas.api_keys_per_member).toBe(2)
    expect(status.license.binding).toBe('unbound')
    const members = await (await page.request.get(`${backend.admin_url}/api/admin/users`)).json()
    expect(members.items.some(item => item.id === identity.id && item.status === 'disabled')).toBe(true)
    await page.setViewportSize({ width: 1366, height: 768 })
    const replay = await importLicense(page, backend.license_files.paid)
    expect(replay.headers()['x-aster-error-number']).toBe('51007')
  } finally { await memberContext.close() }
})

test.describe('expired subscription', () => {
  test.use({ expiredLicense: true })
  test('explicit free switch restores member creation without deleting retained data', async ({ page, backend }) => {
    await page.goto(`${backend.admin_url}/login`)
    await page.getByLabel('管理员邮箱', { exact: true }).fill('owner@example.test')
    await page.getByLabel('密码', { exact: true }).fill('owner-password-strong')
    await page.getByRole('button', { name: '进入管理端', exact: true }).click()
    await expect(page).toHaveURL(/\/overview$/)
    await page.goto(`${backend.admin_url}/license`)
    const failures = captureFailures(page)
    await page.getByRole('button', { name: '切换免费版', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: '确认切换', exact: true }).click()
    await expect(page.getByRole('heading', { name: '免费版已启用', exact: true })).toBeVisible()
    await page.goto(`${backend.admin_url}/users`)
    await expect(page.getByText('retained@example.test', { exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: '新增成员', exact: true })).toBeEnabled()
    await expect(page.getByRole('status').filter({ hasText: '订阅已到期' })).toHaveCount(0)
    expect(failures).toEqual([])
  })
})
