// @generated by tools/codegen/generate-contracts.mjs; DO NOT EDIT.
use serde::{Deserialize, Serialize};
pub const CATALOG_VERSION: u32 = 1;
pub const PRODUCT: &str = "aster-team";
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct UnknownCatalogId;
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum FeatureSetId {
    #[serde(rename = "standard")]
    Standard,
}
impl<'de> Deserialize<'de> for FeatureSetId {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        value
            .parse()
            .map_err(|_| serde::de::Error::custom("unknown FeatureSetId"))
    }
}
impl FeatureSetId {
    pub const ALL: &'static [Self] = &[Self::Standard];
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Standard => "standard",
        }
    }
}
impl std::str::FromStr for FeatureSetId {
    type Err = UnknownCatalogId;
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "standard" => Ok(Self::Standard),
            _ => Err(UnknownCatalogId),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum CapabilityId {
    #[serde(rename = "gateway")]
    Gateway,
    #[serde(rename = "member")]
    Member,
    #[serde(rename = "runner")]
    Runner,
}
impl<'de> Deserialize<'de> for CapabilityId {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        value
            .parse()
            .map_err(|_| serde::de::Error::custom("unknown CapabilityId"))
    }
}
impl CapabilityId {
    pub const ALL: &'static [Self] = &[Self::Gateway, Self::Member, Self::Runner];
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Gateway => "gateway",
            Self::Member => "member",
            Self::Runner => "runner",
        }
    }
}
impl std::str::FromStr for CapabilityId {
    type Err = UnknownCatalogId;
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "gateway" => Ok(Self::Gateway),
            "member" => Ok(Self::Member),
            "runner" => Ok(Self::Runner),
            _ => Err(UnknownCatalogId),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum QuotaId {
    #[serde(rename = "member_seats")]
    MemberSeats,
    #[serde(rename = "runners")]
    Runners,
    #[serde(rename = "upstream_accounts")]
    UpstreamAccounts,
    #[serde(rename = "api_keys_per_member")]
    ApiKeysPerMember,
}
impl<'de> Deserialize<'de> for QuotaId {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        value
            .parse()
            .map_err(|_| serde::de::Error::custom("unknown QuotaId"))
    }
}
impl QuotaId {
    pub const ALL: &'static [Self] = &[
        Self::MemberSeats,
        Self::Runners,
        Self::UpstreamAccounts,
        Self::ApiKeysPerMember,
    ];
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::MemberSeats => "member_seats",
            Self::Runners => "runners",
            Self::UpstreamAccounts => "upstream_accounts",
            Self::ApiKeysPerMember => "api_keys_per_member",
        }
    }
}
impl std::str::FromStr for QuotaId {
    type Err = UnknownCatalogId;
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "member_seats" => Ok(Self::MemberSeats),
            "runners" => Ok(Self::Runners),
            "upstream_accounts" => Ok(Self::UpstreamAccounts),
            "api_keys_per_member" => Ok(Self::ApiKeysPerMember),
            _ => Err(UnknownCatalogId),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum BusinessOperationId {
    #[serde(rename = "upstream_authorize")]
    UpstreamAuthorize,
    #[serde(rename = "upstream_sync")]
    UpstreamSync,
    #[serde(rename = "upstream_refresh")]
    UpstreamRefresh,
}
impl<'de> Deserialize<'de> for BusinessOperationId {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        value
            .parse()
            .map_err(|_| serde::de::Error::custom("unknown BusinessOperationId"))
    }
}
impl BusinessOperationId {
    pub const ALL: &'static [Self] = &[
        Self::UpstreamAuthorize,
        Self::UpstreamSync,
        Self::UpstreamRefresh,
    ];
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::UpstreamAuthorize => "upstream_authorize",
            Self::UpstreamSync => "upstream_sync",
            Self::UpstreamRefresh => "upstream_refresh",
        }
    }
}
impl std::str::FromStr for BusinessOperationId {
    type Err = UnknownCatalogId;
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "upstream_authorize" => Ok(Self::UpstreamAuthorize),
            "upstream_sync" => Ok(Self::UpstreamSync),
            "upstream_refresh" => Ok(Self::UpstreamRefresh),
            _ => Err(UnknownCatalogId),
        }
    }
}

impl BusinessOperationId {
    pub const fn required_capabilities(self) -> &'static [CapabilityId] {
        match self {
            Self::UpstreamAuthorize => &[CapabilityId::Gateway, CapabilityId::Runner],
            Self::UpstreamSync => &[CapabilityId::Gateway, CapabilityId::Runner],
            Self::UpstreamRefresh => &[CapabilityId::Gateway, CapabilityId::Runner],
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum QuotaScope {
    Installation,
    Member,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
pub struct CapabilityDescriptor {
    pub id: CapabilityId,
    pub label: &'static str,
    pub description: &'static str,
    pub feature_set: FeatureSetId,
    pub free_default: bool,
    pub requires: &'static [CapabilityId],
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
pub struct QuotaDescriptor {
    pub id: QuotaId,
    pub label: &'static str,
    pub unit: &'static str,
    pub scope: QuotaScope,
}
pub const CAPABILITIES: &[CapabilityDescriptor] = &[
    CapabilityDescriptor {
        id: CapabilityId::Gateway,
        label: "模型接入",
        description: "模型兼容接口与上游接入管理",
        feature_set: FeatureSetId::Standard,
        free_default: true,
        requires: &[],
    },
    CapabilityDescriptor {
        id: CapabilityId::Member,
        label: "成员协作",
        description: "成员控制台、席位与使用额度管理",
        feature_set: FeatureSetId::Standard,
        free_default: true,
        requires: &[],
    },
    CapabilityDescriptor {
        id: CapabilityId::Runner,
        label: "Runner 执行",
        description: "私有运行节点与任务执行",
        feature_set: FeatureSetId::Standard,
        free_default: true,
        requires: &[],
    },
];
pub const QUOTAS: &[QuotaDescriptor] = &[
    QuotaDescriptor {
        id: QuotaId::MemberSeats,
        label: "成员席位",
        unit: "席位",
        scope: QuotaScope::Installation,
    },
    QuotaDescriptor {
        id: QuotaId::Runners,
        label: "Runner",
        unit: "个",
        scope: QuotaScope::Installation,
    },
    QuotaDescriptor {
        id: QuotaId::UpstreamAccounts,
        label: "订阅/账号",
        unit: "个",
        scope: QuotaScope::Installation,
    },
    QuotaDescriptor {
        id: QuotaId::ApiKeysPerMember,
        label: "每人 Key",
        unit: "个",
        scope: QuotaScope::Member,
    },
];
